[workspace]
members = [
    "crates/pc-nsf-hifigan",
    "crates/pupu-vocoder",
]
resolver = "3"

[workspace.package]
edition = "2024"

[workspace.dependencies]
mlx-rs = { git = "https://github.com/blossom-slopware/mlx-rs.git", rev = "b81194a47c2c6ba4ecb0cf370e4f0d941f52dd5d", features = ["accelerate", "metal"] }
